services:
  headscale:
    image: headscale/headscale:0.25.0
    restart: unless-stopped
    container_name: headscale
    ports:
      - "8081:8080"
      - "8082:9090"
    volumes:
      - ./config:/etc/headscale
    command: serve
